//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTSeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGSTSeller()
        {
            this.tblGSTSellerDocuments = new HashSet<tblGSTSellerDocument>();
            this.tblGSTSellerPayments = new HashSet<tblGSTSellerPayment>();
        }
    
        public int SellerId { get; set; }
        public string SellerCode { get; set; }
        public string SellerFullName { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> BusinessPinCode { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public string AlternateMobileNo { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.DateTime> SellerApprovalDate { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual tblGSTCity tblGSTCity { get; set; }
        public virtual tblGSTStatu tblGSTStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGSTSellerDocument> tblGSTSellerDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGSTSellerPayment> tblGSTSellerPayments { get; set; }
    }
}
