//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTSellerPayment
    {
        public int SellerPaymentId { get; set; }
        public string SellerCode { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentDate { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public string TransactionId { get; set; }
        public string PaymentDoneFile { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual tblGSTSeller tblGSTSeller { get; set; }
        public virtual tblGSTStatu tblGSTStatu { get; set; }
    }
}
