//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTRatingandFeedback
    {
        public int ReviewId { get; set; }
        public string BuyerCode { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> RatingStarNo { get; set; }
        public string FeedbackOnProduct { get; set; }
    
        public virtual tblGSTBuyer tblGSTBuyer { get; set; }
    }
}
