//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTBuyerPayment
    {
        public int PaymentId { get; set; }
        public string PaymentMode { get; set; }
        public string BuyerCode { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string TransactionId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblGSTBuyer tblGSTBuyer { get; set; }
        public virtual tblGSTStatu tblGSTStatu { get; set; }
    }
}
