//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTCouponSetting
    {
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> CouponAmount { get; set; }
        public string CouponRange { get; set; }
        public string ExpiryDays { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual tblGSTStatu tblGSTStatu { get; set; }
    }
}
