//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTSubCategory3
    {
        public int SubCategory3Id { get; set; }
        public string SubCategory3Name { get; set; }
        public string SubCatagory3Code { get; set; }
        public string SubCategory2Code { get; set; }
    }
}
