//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTOrder
    {
        public int OrderId { get; set; }
        public string OrderCode { get; set; }
        public string BuyerCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductQuantity { get; set; }
        public Nullable<int> AddressStatus { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> ShippingCharges { get; set; }
        public Nullable<int> ShareId { get; set; }
        public Nullable<bool> IsNotify { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string RejectedByUserCode { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
