//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGSTOffer()
        {
            this.tblGSTProductOffers = new HashSet<tblGSTProductOffer>();
        }
    
        public int AdminOfferId { get; set; }
        public string OfferName { get; set; }
        public Nullable<int> Offer_ { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> OfferStatusId { get; set; }
    
        public virtual tblGSTStatu tblGSTStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGSTProductOffer> tblGSTProductOffers { get; set; }
    }
}
