//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTSellerDocument
    {
        public int SellerDocumentId { get; set; }
        public string SellerCode { get; set; }
        public string AadharNo { get; set; }
        public string PanCardNo { get; set; }
        public string AadharImage { get; set; }
        public string PanImage { get; set; }
        public string BusinessName { get; set; }
        public string GSTIN { get; set; }
        public Nullable<int> BusinessPinCode { get; set; }
        public string BusinessAadharNo { get; set; }
        public string BusinessPanNo { get; set; }
        public string BusinessAdharImage { get; set; }
        public string BusinessPanImage { get; set; }
    
        public virtual tblGSTSeller tblGSTSeller { get; set; }
    }
}
