//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTAddress
    {
        public int AddressId { get; set; }
        public string UserCode { get; set; }
        public string Home { get; set; }
        public string Office { get; set; }
        public string Other { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual tblGSTStatu tblGSTStatu { get; set; }
    }
}
