//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTProduct
    {
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string CategoryCode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> MinRangeDiscount { get; set; }
        public Nullable<double> MRP { get; set; }
        public string SellerCode { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ProductWeight { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<bool> IsProductReturnable { get; set; }
        public Nullable<bool> IsproductExpirable { get; set; }
        public string ProductExpiryDuration { get; set; }
        public Nullable<bool> IsProductSeasonable { get; set; }
        public string SeasonName { get; set; }
        public string ProductWeightRange { get; set; }
        public Nullable<System.DateTime> ProductRegistrationDate { get; set; }
        public Nullable<System.DateTime> ProductApprovalDate { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<double> MaximumStock { get; set; }
        public Nullable<double> MinimumStock { get; set; }
        public string RejectionReasonfromAdmin { get; set; }
    
        public virtual tblGSTStatu tblGSTStatu { get; set; }
    }
}
