//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSTAgroEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTWallet
    {
        public int WalletId { get; set; }
        public Nullable<int> RewardId { get; set; }
        public string BuyerCode { get; set; }
        public Nullable<int> TotalRewardPoints { get; set; }
        public Nullable<int> UsedRewardPoints { get; set; }
        public string OrderCode { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CouponExpDate { get; set; }
    
        public virtual tblGSTBuyer tblGSTBuyer { get; set; }
        public virtual tblGSTStatu tblGSTStatu { get; set; }
    }
}
